### ISSUE TITLE
IMetadataImport being Marshal.ReleaseCOMObject()-d eagerly?

### ISSUE THREAD

**Issue by KirillOsenkov** [dotnet/symreader-portable#127]
I'm looking at this line:
https://github.com/dotnet/symreader-portable/blob/7380d910e1b06b19c665ad74dc0902c2e5963f8e/src/Microsoft.DiaSymReader.PortablePdb/SymBinder.cs#L323

If I pass an instance of IMetadataReader that I'm using elsewhere, calling it after I called GetReaderFromStream results in `COM object that has been separated from its underlying RCW cannot be used`. 

Am I calling it wrong? Is there a way to counter-act the ReleaseCOMObject call by calling AddRef somehow?

**Comment by KirillOsenkov** [comment]
@pharring says ReleaseComObject shouldn't be used: https://blogs.msdn.microsoft.com/visualstudio/2010/03/01/marshal-releasecomobject-considered-dangerous/

**Comment by KirillOsenkov** [comment]
Looks like I was able to work around using this:
https://stackoverflow.com/a/4370768/37899

**Comment by tmat** [comment]
@gregg-miskelly @tommcdon 

The VS debugger invokes it from native code. I found some other managed code in VS that invokes it like so:

```C#
 public ISymbolReader GetReaderFromStream(Object importer, IStream stream)
        {
            ISymUnmanagedReader reader = null;
            IntPtr uImporter = IntPtr.Zero;
            try
            {
                uImporter = Marshal.GetIUnknownForObject(importer);
                int hr = binder.GetReaderFromStream(uImporter, stream, out reader);
                if (IsFailingResultNormal(hr))
                {
                    return null;
                }
                Marshal.ThrowExceptionForHR(hr);
            }
            finally
            {
                if (uImporter != IntPtr.Zero)
                    Marshal.Release(uImporter);
            }
            return new SymReader(reader);
        }
```

**Comment by gregg-miskelly** [comment]
While with well behaved COM interfaces I would agree that ReleaseComObject is good to avoid, IMetaDataImport is NOT well behaved - that API will lock files and the CLR team never provided a general purpose Dispose. So if you want to use that API from managed code, unless you know you will only use it in a short-lived process, you **MUST** use ReleaseComObject.

The code that is quoted above looks reasonable to me. 

If you are only dealing with symbol readers that support the new interface, you can also use the ISymUnmanagedBinder4 interfaces.

**Comment by KirillOsenkov** [comment]
Aha, the code above does essentially what my workaround does - by calling GetIUnknownForObject it increments the refcount on the RCW that wraps the importer, to counterbalance the ReleaseComObject call inside. 

It all checks out now.

**Comment by KirillOsenkov** [comment]
FYI this is how I AddRef on the RCW:
```
public static T AddRcwRef<T>(T t) 
{
    IntPtr ptr = Marshal.GetIUnknownForObject(t);
    try {
        return (T)Marshal.GetObjectForIUnknown(ptr);
    }
    finally {
         Marshal.Release(ptr); // done with the IntPtr
    }
}
```
