### ISSUE TITLE
Question: Need a quick example how to read the list of documents in a PDB file

### ISSUE THREAD

**Issue by danwalmsley** [dotnet/symreader-portable#65]
Hi, I'm looking at custom .net debugger, and I'm trying to read the PDB file to load symbols, etc

First thing I need to do is load the document table.

Is there an example of how to do this, so far I have tried things like... 

```
ISymUnmanagedReader reader = null;
                new SymBinder().GetReaderFromStream(new SymMetadataImport(File.OpenRead(assemblyPath)), File.OpenRead(str), out reader);
```

this just returns null. (assembly path = helloworld.dll, and str contains helloworld.pdb)

I am trying to read from pdb file generated by .net core.

The metadataimport argument has me stumped a little too!

Thanks in advace.

**Comment by tmat** [comment]
Sorry for the delayed response. If you are reading Portable PDB (PDB generated by .NET Core projects) you should use System.Reflection.Metadata APIs. 

The specification for the format is here: https://github.com/dotnet/corefx/blob/master/src/System.Reflection.Metadata/specs/PortablePdb-Metadata.md

An example of reading documents (and other information) is here: https://github.com/dotnet/metadata-tools/blob/master/src/Microsoft.Metadata.Visualizer/MetadataVisualizer.cs#L1655
